# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\myself\image_Registration\segmentation.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1250, 1144)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 1050, 1080))
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(10, 40, 1034, 1034))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sarlabel = QtWidgets.QLabel(self.widget)
        self.sarlabel.setMinimumSize(QtCore.QSize(512, 512))
        self.sarlabel.setMaximumSize(QtCore.QSize(512, 512))
        self.sarlabel.setObjectName("sarlabel")
        self.horizontalLayout.addWidget(self.sarlabel)
        self.optlabel = QtWidgets.QLabel(self.widget)
        self.optlabel.setMinimumSize(QtCore.QSize(512, 512))
        self.optlabel.setMaximumSize(QtCore.QSize(512, 512))
        self.optlabel.setObjectName("optlabel")
        self.horizontalLayout.addWidget(self.optlabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.reslabel = QtWidgets.QLabel(self.widget)
        self.reslabel.setMinimumSize(QtCore.QSize(1024, 512))
        self.reslabel.setMaximumSize(QtCore.QSize(1024, 512))
        self.reslabel.setObjectName("reslabel")
        self.verticalLayout.addWidget(self.reslabel)
        self.sarbtn = QtWidgets.QPushButton(self.centralwidget)
        self.sarbtn.setGeometry(QtCore.QRect(1080, 60, 150, 50))
        self.sarbtn.setObjectName("sarbtn")
        self.optbtn = QtWidgets.QPushButton(self.centralwidget)
        self.optbtn.setGeometry(QtCore.QRect(1080, 130, 150, 50))
        self.optbtn.setObjectName("optbtn")
        self.rebtn = QtWidgets.QPushButton(self.centralwidget)
        self.rebtn.setGeometry(QtCore.QRect(1080, 200, 150, 50))
        self.rebtn.setObjectName("rebtn")

        # 创建字体对象
        font = QtGui.QFont()
        # 设置字体大小，例如设置为14
        font.setPointSize(12)
        font.setBold(True)
        # 设置 `mse_label` 的字体
        self.mse_label = QtWidgets.QLabel(self.centralwidget)
        self.mse_label.setFont(font)
        self.mse_label.setGeometry(QtCore.QRect(1090, 500, 150, 50))  # 定位在按钮下方
        self.mse_label.setMinimumSize(QtCore.QSize(150, 50))  # 设置合适的大小
        self.mse_label.setMaximumSize(QtCore.QSize(150, 50))
        self.mse_label.setObjectName("mse_label")
        self.mse_label.setText("MSE: 0.0000")  # 初始 MSE 值

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1239, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "图像配准系统"))
        self.groupBox.setTitle(_translate("MainWindow", "图像配准系统"))
        self.sarlabel.setText(_translate("MainWindow", "图像"))
        self.optlabel.setText(_translate("MainWindow", "图像"))
        self.reslabel.setText(_translate("MainWindow", "图像"))
        self.sarbtn.setText(_translate("MainWindow", "导入SAR"))
        self.optbtn.setText(_translate("MainWindow", "导入OPT"))
        self.rebtn.setText(_translate("MainWindow", "配准"))
